repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: alembic_folder/versions
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
        files: '\.sh$|^Dockerfile$|^Makefile$'
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: name-tests-test
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      additional_dependencies: [ types-PyYAML==6.0.8, types-requests==2.28.11.2 ]
