# SPDX-FileCopyrightText: Contributors to the utility-route-project and Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Quality checks
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        shell: bash
        run: poetry install
      - name: Run pre-commit
        shell: bash
        run: poetry run pre-commit run --all-files
      - name: Run unit and integration tests
        shell: bash
        run: poetry run pytest tests
